apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-gitops-runtime
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: default
  source:
    repoURL: https://github.com/vasil-cf/argo-local-configs.git
    targetRevision: HEAD
    path: resources/gitops-runtime-local-01/chart
    helm:
      releaseName: cf-gitops-runtime
  destination:
    namespace: gitops-runtime-local-01
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
