apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-git-source1
  labels:
    codefresh.io/entity: 'git-source'
    codefresh.io/internal: 'false'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cf-git-sources
  sources:
    - repoURL: https://github.com/vasil-cf/local-git-source-01.git
      path: git-source1
      targetRevision: main
      directory:
        include: '*'
        exclude: ''
        recurse: true
  destination:
    namespace: gitops-runtime-local-01
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
