apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-default-promotion-workflows-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cf-default-promotion-workflows-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
    - argoproj.io
    resources:
    - workflowtaskresults
    verbs:
    - create
    - get
    - list
    - patch
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-default-promotion-workflows-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cf-default-promotion-workflows-role
subjects:
  - kind: ServiceAccount
    name: cf-default-promotion-workflows-sa
